version: '1.0.{build}'

os: Visual Studio 2017

environment:
  matrix:
  - Toolset: v150
  - Toolset: v140

platform:
  - Win32
  - x64

configuration:
#  - Release
  - Debug

build:
  verbosity: Detailed

artifacts:
  - path: 'build/*'
    name: temp

before_build:
- ps: |
    Write-Output "Configuration: $env:CONFIGURATION"
    Write-Output "Platform: $env:PLATFORM"
    $generator = switch ($env:TOOLSET)
    {
      "v150" {"Visual Studio 15 2017"}
      "v140" {"Visual Studio 14 2015"}
    }
    if ($env:PLATFORM -eq "x64")
    {
      $generator = "$generator Win64"
    }

build_script:
- ps: |
    md build -Force | Out-Null
    cd build

    & cmake -G "$generator" -DCMAKE_CONFIGURATION_TYPES="Debug;Release" ..
    if ($LastExitCode -ne 0) {
      throw "Exec: $ErrorMessage"
    }
    & cmake --build . --config $env:CONFIGURATION
    if ($LastExitCode -ne 0) {
      throw "Exec: $ErrorMessage"
    }
    & ctest -VV
    if ($LastExitCode -ne 0) {
      throw "Exec: $ErrorMessage"
    }
